name: "Ankit Kumar Generic Infra code"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  TF_DIR: environment/dev/
  client-id: ${{ secrets.AZURE_CLIENT_ID }}
  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: [self-hosted, Ankit-GenericInfra]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login using OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ env.client-id }}
          tenant-id: ${{ env.tenant-id }}
          subscription-id: ${{ env.subscription-id }}

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init --var "subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"

      - name: Run Tfsec
        run: tfsec . --format junit --out tfsec.xml 

      - name: Run Trivy
        run: trivy config --format json --output trivy-tf.json . 

      - name: Run Checkov
        run: checkov -d . -o junitxml --soft-fail > checkov.xml 

      # ðŸ“¦ Always upload reports
      - name: Upload security scan artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-security-reports
          path: |
            tfsec.xml
            trivy-tf.json
            checkov.xml
